/** User-facing strings for the Cupboard app, centralised for future localisation. */

export const APP_NAME = 'Cupboard';

export const TAB_LABELS = {
  PANTRY: 'Pantry',
  RECIPES: 'Recipes',
  SCAN: 'Scan',
  PROFILE: 'Profile',
} as const;

export const PANTRY_STRINGS = {
  TITLE: 'My Pantry',
  EMPTY_STATE: 'Your pantry is empty. Add items by scanning or entering them manually.',
  ADD_ITEM: 'Add Item',
  EDIT_ITEM: 'Edit Item',
  DELETE_ITEM: 'Delete Item',
  DELETE_CONFIRM: 'Are you sure you want to delete this item?',
  SEARCH_PLACEHOLDER: 'Search pantry items...',
  NAME_LABEL: 'Name',
  NAME_PLACEHOLDER: 'e.g. Milk',
  QUANTITY_LABEL: 'Quantity',
  UNIT_LABEL: 'Unit',
  CATEGORY_LABEL: 'Category',
  EXPIRY_LABEL: 'Expiry Date (optional)',
  BARCODE_LABEL: 'Barcode',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  ITEM_ADDED: 'Item added to pantry',
  ITEM_UPDATED: 'Item updated',
  ITEM_DELETED: 'Item removed from pantry',
  QUICK_ADD: 'Quick Add',
  BULK_DELETE: 'Bulk Delete',
  SELECT_ALL: 'Select All',
  DELETE_SELECTED: 'Delete Selected',
} as const;

export const RECIPE_STRINGS = {
  TITLE: 'Recipes',
  EMPTY_STATE: 'No recipes yet. Create one or discover recipes based on your pantry.',
  ADD_RECIPE: 'Add Recipe',
  EDIT_RECIPE: 'Edit Recipe',
  DELETE_RECIPE: 'Delete Recipe',
  DELETE_CONFIRM: 'Are you sure you want to delete this recipe?',
  MARK_AS_MADE: 'Mark as Made',
  MADE_CONFIRM: 'Mark this recipe as made? Ingredients will be deducted from your pantry.',
  FAVOURITE: 'Favourite',
  UNFAVOURITE: 'Unfavourite',
  TITLE_LABEL: 'Title',
  TITLE_PLACEHOLDER: 'e.g. Pasta Carbonara',
  DESCRIPTION_LABEL: 'Description',
  DESCRIPTION_PLACEHOLDER: 'A brief description of the recipe...',
  INGREDIENTS_LABEL: 'Ingredients',
  STEPS_LABEL: 'Steps',
  TAGS_LABEL: 'Tags',
  TAGS_PLACEHOLDER: 'e.g. Italian, Quick, Vegetarian',
  IMPORT_URL: 'Import from URL',
  IMPORT_TEXT: 'Import from Text',
  SCAN_RECIPE: 'Scan Recipe',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  CAN_MAKE_NOW: 'Can make now',
  ALMOST_THERE: 'Almost there',
  MISSING_A_FEW: 'Missing a few',
  MISSING_INGREDIENTS: 'Missing %d ingredient(s)',
  RECIPE_SAVED: 'Recipe saved',
  RECIPE_DELETED: 'Recipe deleted',
  INGREDIENTS_DEDUCTED: 'Ingredients deducted from pantry',
} as const;

export const SCAN_STRINGS = {
  TITLE: 'Scan',
  BARCODE_SCAN: 'Scan Barcode',
  RECEIPT_SCAN: 'Scan Receipt',
  INGREDIENT_SCAN: 'Identify Ingredients',
  RECIPE_SCAN: 'Scan Recipe',
  CAMERA_PERMISSION_TITLE: 'Camera Permission Required',
  CAMERA_PERMISSION_MESSAGE: 'Cupboard needs access to your camera to scan items. Please enable camera access in your device settings.',
  OPEN_SETTINGS: 'Open Settings',
  SCANNING: 'Scanning...',
  PROCESSING: 'Processing image...',
  NO_RESULTS: 'No items detected. Try again with better lighting.',
  PRODUCT_FOUND: 'Product Found',
  PRODUCT_NOT_FOUND: 'Product not found in database. You can add it manually.',
  REVIEW_ITEMS: 'Review Detected Items',
  CONFIRM_ADD: 'Add to Pantry',
  RETAKE: 'Retake',
} as const;

export const AUTH_STRINGS = {
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  SIGN_OUT: 'Sign Out',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Your password',
  DISPLAY_NAME_LABEL: 'Display Name',
  DISPLAY_NAME_PLACEHOLDER: 'Your name',
  FORGOT_PASSWORD: 'Forgot Password?',
  NO_ACCOUNT: "Don't have an account?",
  HAS_ACCOUNT: 'Already have an account?',
  GOOGLE_SIGN_IN: 'Continue with Google',
  SIGN_IN_ERROR: 'Unable to sign in. Please check your credentials.',
  SIGN_UP_ERROR: 'Unable to create account. Please try again.',
  SIGN_OUT_CONFIRM: 'Are you sure you want to sign out?',
} as const;

export const PROFILE_STRINGS = {
  TITLE: 'Profile',
  DIETARY_RESTRICTIONS: 'Dietary Restrictions',
  CUISINE_PREFERENCES: 'Cuisine Preferences',
  SAVE_PREFERENCES: 'Save Preferences',
  PREFERENCES_SAVED: 'Preferences saved',
} as const;

export const COMMON_STRINGS = {
  LOADING: 'Loading...',
  ERROR: 'Something went wrong. Please try again.',
  RETRY: 'Retry',
  OK: 'OK',
  YES: 'Yes',
  NO: 'No',
  DONE: 'Done',
  NEXT: 'Next',
  BACK: 'Back',
  CLOSE: 'Close',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  EDIT: 'Edit',
  ADD: 'Add',
  SEARCH: 'Search',
  FILTER: 'Filter',
  SORT: 'Sort',
  NO_RESULTS: 'No results found.',
  OFFLINE: 'You are offline. Changes will sync when you reconnect.',
} as const;
